# Generated by Django 5.0.6 on 2024-07-09 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donate_blood/images/')),
                ('mobile_no', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('address', models.TextField()),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('is_available_for_donation', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('blood_group', models.CharField(choices=[('0+', '0+'), ('A+', 'A+'), ('B+', 'B+')], max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate_blood.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='DonatioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Accepted', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('donation_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation', to='donate_blood.donationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate_blood.useraccount')),
            ],
        ),
    ]
