# Generated by Django 5.0.6 on 2024-07-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_blood', '0002_alter_donatiohistory_user_alter_donationrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='patient_name',
            field=models.CharField(default='patient', max_length=100),
        ),
        migrations.AlterField(
            model_name='donatiohistory',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=50),
        ),
    ]
