# Generated by Django 5.0.6 on 2024-07-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate_blood', '0003_donationrequest_patient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatiohistory',
            old_name='donation_request_id',
            new_name='donation_request',
        ),
    ]
