# Generated by Django 5.0.6 on 2024-07-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_blood', '0004_rename_donation_request_id_donatiohistory_donation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=50),
        ),
    ]
