# Generated by Django 5.0.6 on 2024-07-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_blood', '0005_useraccount_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
