# Generated by Django 5.0.6 on 2024-07-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_blood', '0006_donationrequest_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donate_blood/images/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
