# Generated by Django 5.0.6 on 2024-08-15 05:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate_blood', '0011_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
