# Generated by Django 5.1.1 on 2024-10-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_blood', '0012_alter_useraccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
